"""creation schema complet

Revision ID: 2231c3c4a1ca
Revises: 
Create Date: 2026-07-23 13:36:46.757943

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '2231c3c4a1ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('couleur', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.CheckConstraint("couleur IS NULL OR couleur ~ '^#[0-9A-Fa-f]{6}$'", name='chk_couleur_hex'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('departements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departements_nom'), 'departements', ['nom'], unique=True)
    op.create_table('utilisateurs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mot_de_passe_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('administrateur', 'collaborateur', name='role_utilisateur'), server_default='collaborateur', nullable=False),
    sa.Column('poste', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('departement_id', sa.Uuid(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_derniere_connexion', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_table('formations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('categorie_id', sa.Uuid(), nullable=False),
    sa.Column('obligatoire', sa.Boolean(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('duree_estimee_minutes', sa.Integer(), nullable=True),
    sa.Column('cree_par', sa.Uuid(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.CheckConstraint('duree_estimee_minutes IS NULL OR duree_estimee_minutes > 0', name='chk_duree_formation'),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['cree_par'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('formation', 'quiz', 'certificat', 'rappel', 'systeme', name='type_notification'), nullable=False),
    sa.Column('titre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lien', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('lu', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affectations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('formation_id', sa.Uuid(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=True),
    sa.Column('departement_id', sa.Uuid(), nullable=True),
    sa.Column('affecte_par', sa.Uuid(), nullable=False),
    sa.Column('date_affectation', sa.DateTime(), nullable=False),
    sa.Column('date_limite', sa.Date(), nullable=True),
    sa.CheckConstraint('(utilisateur_id IS NOT NULL AND departement_id IS NULL) OR (utilisateur_id IS NULL AND departement_id IS NOT NULL)', name='chk_affectation_cible'),
    sa.CheckConstraint('date_limite IS NULL OR date_limite >= date_affectation::DATE', name='chk_date_limite'),
    sa.ForeignKeyConstraint(['affecte_par'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contenus',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('formation_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('video', 'pdf', 'presentation', 'lien', 'document', name='type_contenu'), nullable=False),
    sa.Column('titre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('chemin_fichier', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('duree_secondes', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.CheckConstraint('duree_secondes IS NULL OR duree_secondes >= 0', name='chk_duree_contenu'),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formation_id', 'ordre', name='uq_contenu_ordre')
    )
    op.create_table('questionnaires',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('formation_id', sa.Uuid(), nullable=False),
    sa.Column('titre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('score_minimum_reussite', sa.Integer(), nullable=False),
    sa.Column('nombre_tentatives_max', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.CheckConstraint('nombre_tentatives_max IS NULL OR nombre_tentatives_max > 0', name='chk_nombre_tentatives'),
    sa.CheckConstraint('score_minimum_reussite BETWEEN 0 AND 100', name='chk_score_reussite'),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progressions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=False),
    sa.Column('formation_id', sa.Uuid(), nullable=False),
    sa.Column('affectation_id', sa.Uuid(), nullable=False),
    sa.Column('statut', sa.Enum('non_commence', 'en_cours', 'termine', name='statut_progression'), server_default='non_commence', nullable=False),
    sa.Column('pourcentage', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('derniere_activite', sa.DateTime(), nullable=True),
    sa.CheckConstraint('date_fin IS NULL OR date_debut IS NULL OR date_fin >= date_debut', name='chk_dates_progression'),
    sa.CheckConstraint('pourcentage BETWEEN 0 AND 100', name='chk_progression'),
    sa.ForeignKeyConstraint(['affectation_id'], ['affectations.id'], ),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id', 'formation_id', name='uq_progression_utilisateur_formation')
    )
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('questionnaire_id', sa.Uuid(), nullable=False),
    sa.Column('enonce', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.CheckConstraint('points > 0', name='chk_points'),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('questionnaire_id', 'ordre', name='uq_question_ordre')
    )
    op.create_table('tentatives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=False),
    sa.Column('questionnaire_id', sa.Uuid(), nullable=False),
    sa.Column('numero_tentative', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reussi', sa.Boolean(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_passage', sa.DateTime(), nullable=False),
    sa.CheckConstraint('date_passage >= date_debut', name='chk_dates_tentative'),
    sa.CheckConstraint('numero_tentative > 0', name='chk_numero_tentative'),
    sa.CheckConstraint('score BETWEEN 0 AND 100', name='chk_score'),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id', 'questionnaire_id', 'numero_tentative', name='uq_numero_tentative')
    )
    op.create_table('certificats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('utilisateur_id', sa.Uuid(), nullable=False),
    sa.Column('formation_id', sa.Uuid(), nullable=False),
    sa.Column('tentative_id', sa.Uuid(), nullable=True),
    sa.Column('numero_certificat', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fichier_pdf', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('date_obtention', sa.DateTime(), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=True),
    sa.CheckConstraint('date_expiration IS NULL OR date_expiration >= date_obtention::DATE', name='chk_date_expiration'),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.ForeignKeyConstraint(['tentative_id'], ['tentatives.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_certificat')
    )
    op.create_table('reponses_possibles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('texte', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('est_correcte', sa.Boolean(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'ordre', name='uq_reponse_ordre')
    )
    op.create_table('reponses_utilisateur',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tentative_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('reponse_possible_id', sa.Uuid(), nullable=False),
    sa.Column('est_correcte', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['reponse_possible_id'], ['reponses_possibles.id'], ),
    sa.ForeignKeyConstraint(['tentative_id'], ['tentatives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tentative_id', 'question_id', name='uq_reponse_question')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reponses_utilisateur')
    op.drop_table('reponses_possibles')
    op.drop_table('certificats')
    op.drop_table('tentatives')
    op.drop_table('questions')
    op.drop_table('progressions')
    op.drop_table('questionnaires')
    op.drop_table('contenus')
    op.drop_table('affectations')
    op.drop_table('notifications')
    op.drop_table('formations')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_departements_nom'), table_name='departements')
    op.drop_table('departements')
    op.drop_table('categories')
    # ### end Alembic commands ###

