"""ajout pipeline ingestion IA (pgvector)

Revision ID: 5866dcc8a1bb
Revises: d81122ca2026
Create Date: 2026-08-05 01:01:43.412962

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector


revision = '5866dcc8a1bb'
down_revision = 'd81122ca2026'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contenu_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contenu_id', sa.UUID(), nullable=False),
    sa.Column('texte', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('embedding',Vector(dim=384), nullable=False),
    sa.ForeignKeyConstraint(['contenu_id'], ['contenus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contenu_chunks')
    # ### end Alembic commands ###
