"""ajout affectations progressions et ondelete

Revision ID: c432bb420c4e
Revises: 2231c3c4a1ca
Create Date: 2026-07-25 15:26:22.829125

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'c432bb420c4e'
down_revision = '2231c3c4a1ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('affectations_utilisateur_id_fkey', 'affectations', type_='foreignkey')
    op.drop_constraint('affectations_formation_id_fkey', 'affectations', type_='foreignkey')
    op.drop_constraint('affectations_departement_id_fkey', 'affectations', type_='foreignkey')
    op.drop_constraint('affectations_affecte_par_fkey', 'affectations', type_='foreignkey')
    op.create_foreign_key(None, 'affectations', 'departements', ['departement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'affectations', 'formations', ['formation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'affectations', 'utilisateurs', ['affecte_par'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'affectations', 'utilisateurs', ['utilisateur_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('contenus_formation_id_fkey', 'contenus', type_='foreignkey')
    op.create_foreign_key(None, 'contenus', 'formations', ['formation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('formations_categorie_id_fkey', 'formations', type_='foreignkey')
    op.drop_constraint('formations_cree_par_fkey', 'formations', type_='foreignkey')
    op.create_foreign_key(None, 'formations', 'utilisateurs', ['cree_par'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'formations', 'categories', ['categorie_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('progressions_formation_id_fkey', 'progressions', type_='foreignkey')
    op.drop_constraint('progressions_affectation_id_fkey', 'progressions', type_='foreignkey')
    op.drop_constraint('progressions_utilisateur_id_fkey', 'progressions', type_='foreignkey')
    op.create_foreign_key(None, 'progressions', 'formations', ['formation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'progressions', 'affectations', ['affectation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'progressions', 'utilisateurs', ['utilisateur_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('utilisateurs_departement_id_fkey', 'utilisateurs', type_='foreignkey')
    op.create_foreign_key(None, 'utilisateurs', 'departements', ['departement_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'utilisateurs', type_='foreignkey')
    op.create_foreign_key('utilisateurs_departement_id_fkey', 'utilisateurs', 'departements', ['departement_id'], ['id'])
    op.drop_constraint(None, 'progressions', type_='foreignkey')
    op.drop_constraint(None, 'progressions', type_='foreignkey')
    op.drop_constraint(None, 'progressions', type_='foreignkey')
    op.create_foreign_key('progressions_utilisateur_id_fkey', 'progressions', 'utilisateurs', ['utilisateur_id'], ['id'])
    op.create_foreign_key('progressions_affectation_id_fkey', 'progressions', 'affectations', ['affectation_id'], ['id'])
    op.create_foreign_key('progressions_formation_id_fkey', 'progressions', 'formations', ['formation_id'], ['id'])
    op.drop_constraint(None, 'formations', type_='foreignkey')
    op.drop_constraint(None, 'formations', type_='foreignkey')
    op.create_foreign_key('formations_cree_par_fkey', 'formations', 'utilisateurs', ['cree_par'], ['id'])
    op.create_foreign_key('formations_categorie_id_fkey', 'formations', 'categories', ['categorie_id'], ['id'])
    op.drop_constraint(None, 'contenus', type_='foreignkey')
    op.create_foreign_key('contenus_formation_id_fkey', 'contenus', 'formations', ['formation_id'], ['id'])
    op.drop_constraint(None, 'affectations', type_='foreignkey')
    op.drop_constraint(None, 'affectations', type_='foreignkey')
    op.drop_constraint(None, 'affectations', type_='foreignkey')
    op.drop_constraint(None, 'affectations', type_='foreignkey')
    op.create_foreign_key('affectations_affecte_par_fkey', 'affectations', 'utilisateurs', ['affecte_par'], ['id'])
    op.create_foreign_key('affectations_departement_id_fkey', 'affectations', 'departements', ['departement_id'], ['id'])
    op.create_foreign_key('affectations_formation_id_fkey', 'affectations', 'formations', ['formation_id'], ['id'])
    op.create_foreign_key('affectations_utilisateur_id_fkey', 'affectations', 'utilisateurs', ['utilisateur_id'], ['id'])
    # ### end Alembic commands ###

