"""ajout commentaires formation

Revision ID: c804c65a66a0
Revises: b07db1ad4d24
Create Date: 2026-08-12 00:08:40.073840

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'c804c65a66a0'
down_revision = 'b07db1ad4d24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentaires',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('formation_id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('contenu', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['commentaires.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commentaire_likes',
    sa.Column('commentaire_id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commentaire_id'], ['commentaires.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('commentaire_id', 'utilisateur_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commentaire_likes')
    op.drop_table('commentaires')
    # ### end Alembic commands ###

