"""ajout quiz certificats notifications et ondelete

Revision ID: d81122ca2026
Revises: c432bb420c4e
Create Date: 2026-07-27 12:37:10.619277

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'd81122ca2026'
down_revision = 'c432bb420c4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('certificats_tentative_id_fkey', 'certificats', type_='foreignkey')
    op.drop_constraint('certificats_formation_id_fkey', 'certificats', type_='foreignkey')
    op.drop_constraint('certificats_utilisateur_id_fkey', 'certificats', type_='foreignkey')
    op.create_foreign_key(None, 'certificats', 'formations', ['formation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'certificats', 'tentatives', ['tentative_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'certificats', 'utilisateurs', ['utilisateur_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('notifications_utilisateur_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'utilisateurs', ['utilisateur_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('questionnaires_formation_id_fkey', 'questionnaires', type_='foreignkey')
    op.create_foreign_key(None, 'questionnaires', 'formations', ['formation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('questions_questionnaire_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'questionnaires', ['questionnaire_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reponses_possibles_question_id_fkey', 'reponses_possibles', type_='foreignkey')
    op.create_foreign_key(None, 'reponses_possibles', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reponses_utilisateur_reponse_possible_id_fkey', 'reponses_utilisateur', type_='foreignkey')
    op.drop_constraint('reponses_utilisateur_tentative_id_fkey', 'reponses_utilisateur', type_='foreignkey')
    op.drop_constraint('reponses_utilisateur_question_id_fkey', 'reponses_utilisateur', type_='foreignkey')
    op.create_foreign_key(None, 'reponses_utilisateur', 'tentatives', ['tentative_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reponses_utilisateur', 'reponses_possibles', ['reponse_possible_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reponses_utilisateur', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tentatives_utilisateur_id_fkey', 'tentatives', type_='foreignkey')
    op.drop_constraint('tentatives_questionnaire_id_fkey', 'tentatives', type_='foreignkey')
    op.create_foreign_key(None, 'tentatives', 'utilisateurs', ['utilisateur_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tentatives', 'questionnaires', ['questionnaire_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tentatives', type_='foreignkey')
    op.drop_constraint(None, 'tentatives', type_='foreignkey')
    op.create_foreign_key('tentatives_questionnaire_id_fkey', 'tentatives', 'questionnaires', ['questionnaire_id'], ['id'])
    op.create_foreign_key('tentatives_utilisateur_id_fkey', 'tentatives', 'utilisateurs', ['utilisateur_id'], ['id'])
    op.drop_constraint(None, 'reponses_utilisateur', type_='foreignkey')
    op.drop_constraint(None, 'reponses_utilisateur', type_='foreignkey')
    op.drop_constraint(None, 'reponses_utilisateur', type_='foreignkey')
    op.create_foreign_key('reponses_utilisateur_question_id_fkey', 'reponses_utilisateur', 'questions', ['question_id'], ['id'])
    op.create_foreign_key('reponses_utilisateur_tentative_id_fkey', 'reponses_utilisateur', 'tentatives', ['tentative_id'], ['id'])
    op.create_foreign_key('reponses_utilisateur_reponse_possible_id_fkey', 'reponses_utilisateur', 'reponses_possibles', ['reponse_possible_id'], ['id'])
    op.drop_constraint(None, 'reponses_possibles', type_='foreignkey')
    op.create_foreign_key('reponses_possibles_question_id_fkey', 'reponses_possibles', 'questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_questionnaire_id_fkey', 'questions', 'questionnaires', ['questionnaire_id'], ['id'])
    op.drop_constraint(None, 'questionnaires', type_='foreignkey')
    op.create_foreign_key('questionnaires_formation_id_fkey', 'questionnaires', 'formations', ['formation_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_utilisateur_id_fkey', 'notifications', 'utilisateurs', ['utilisateur_id'], ['id'])
    op.drop_constraint(None, 'certificats', type_='foreignkey')
    op.drop_constraint(None, 'certificats', type_='foreignkey')
    op.drop_constraint(None, 'certificats', type_='foreignkey')
    op.create_foreign_key('certificats_utilisateur_id_fkey', 'certificats', 'utilisateurs', ['utilisateur_id'], ['id'])
    op.create_foreign_key('certificats_formation_id_fkey', 'certificats', 'formations', ['formation_id'], ['id'])
    op.create_foreign_key('certificats_tentative_id_fkey', 'certificats', 'tentatives', ['tentative_id'], ['id'])
    # ### end Alembic commands ###

